# Generated by Django 4.2.16 on 2026-04-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/sources/')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('target_platform', models.CharField(choices=[('tiktok', 'TikTok'), ('reels', 'Instagram Reels'), ('shorts', 'YouTube Shorts'), ('all', 'Toutes plateformes')], default='all', max_length=20)),
                ('target_clip_count', models.PositiveIntegerField(default=5)),
                ('min_clip_duration', models.FloatField(default=20.0)),
                ('max_clip_duration', models.FloatField(default=60.0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploadé'), ('extracting', 'Extraction'), ('analyzing', 'Analyse IA'), ('generating', 'Génération clips'), ('done', 'Terminé'), ('failed', 'Échoué')], default='uploaded', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Attention'), ('error', 'Erreur')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='videos.video')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/clips/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('composite_score', models.FloatField(default=0.0)),
                ('audio_score', models.FloatField(default=0.0)),
                ('nlp_score', models.FloatField(default=0.0)),
                ('visual_score', models.FloatField(default=0.0)),
                ('transcript', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('reels', 'Instagram Reels'), ('shorts', 'YouTube Shorts')], default='tiktok', max_length=20)),
                ('suggested_title', models.CharField(blank=True, max_length=500)),
                ('suggested_hashtags', models.JSONField(blank=True, default=list)),
                ('best_publish_day', models.CharField(blank=True, max_length=20)),
                ('best_publish_time', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('generating', 'Génération'), ('ready', 'Prêt'), ('failed', 'Échoué')], default='generating', max_length=20)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='videos.video')),
            ],
            options={
                'verbose_name': 'Clip',
                'verbose_name_plural': 'Clips',
                'ordering': ['rank', '-composite_score'],
            },
        ),
    ]
