# Generated by Django 5.2.8 on 2026-04-19 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='tiktok_publish_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clip',
            name='tiktok_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=200)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('scope', models.CharField(blank=True, max_length=300)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte TikTok',
                'verbose_name_plural': 'Comptes TikTok',
            },
        ),
    ]
